"""Tiny self-contained HTML helpers shared by both report renderers.

No external assets: every page carries its own inline CSS.
"""

from __future__ import annotations

import html
from typing import Any, Iterable, List

# Shared inline stylesheet (kept intentionally small and dependency-free).
CSS = """
:root { color-scheme: light; }
* { box-sizing: border-box; }
body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;
       margin: 0; padding: 24px; color: #1a1f29; background: #f4f6fa; }
h1 { font-size: 22px; margin: 0 0 4px; }
h2 { font-size: 16px; margin: 28px 0 10px; }
.sub { color: #5a6472; margin: 0 0 20px; font-size: 13px; }
.tiles { display: flex; flex-wrap: wrap; gap: 12px; margin-bottom: 8px; }
.tile { background: #fff; border: 1px solid #e2e7ef; border-radius: 10px;
        padding: 14px 18px; min-width: 120px; box-shadow: 0 1px 2px rgba(0,0,0,.03); }
.tile .n { font-size: 24px; font-weight: 700; }
.tile .l { font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: .04em; }
table { border-collapse: collapse; width: 100%; background: #fff; border-radius: 10px;
        overflow: hidden; box-shadow: 0 1px 2px rgba(0,0,0,.03); font-size: 13px; }
th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #eef1f6; }
th { background: #eef2f8; font-weight: 600; }
tr:last-child td { border-bottom: none; }
.mono { font-family: ui-monospace, SFMono-Regular, Consolas, monospace; }
.good { color: #0a7d34; }
.bad { color: #b4231c; }
.pill { display: inline-block; padding: 2px 9px; border-radius: 999px; font-size: 12px;
        font-weight: 600; }
.pass { background: #dff3e4; color: #0a7d34; }
.fail { background: #fbe0de; color: #b4231c; }
.err  { background: #fbe0de; color: #b4231c; }
.warn { background: #fdf1d6; color: #8a5a00; }
.info { background: #e2ecfb; color: #23508a; }
.blk  { background: #ece1fb; color: #5b3aa5; }
.ceil { background: #e2eef0; color: #2b6a72; }
.gap  { background: #f0e6dc; color: #8a5a2b; }
.nc   { background: #e7eaef; color: #55606f; }
.card { background: #fff; border: 1px solid #e2e7ef; border-left-width: 5px;
        border-radius: 10px; padding: 14px 18px; margin-bottom: 12px; }
.card.pass { border-left-color: #23a55a; } .card.fail { border-left-color: #d9382e; }
.card.warn { border-left-color: #e0a300; } .card.info { border-left-color: #3f74c9; }
.card.nc   { border-left-color: #9aa4b2; }
.card h3 { margin: 0 0 4px; font-size: 15px; }
.card .detail { color: #47505f; font-size: 13px; margin-bottom: 8px; }
.bar { height: 8px; background: #eceff4; border-radius: 4px; overflow: hidden; min-width: 80px; }
.bar > span { display: block; height: 100%; }
footer { margin-top: 28px; color: #98a2b3; font-size: 12px; }
"""


def esc(v: Any) -> str:
    return html.escape("" if v is None else str(v))


def page(title: str, body: str) -> str:
    return (
        "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        f"<title>{esc(title)}</title><style>{CSS}</style></head><body>{body}"
        "<footer>Generated by the egocentric-episode QA tool.</footer>"
        "</body></html>"
    )


def tile(number: Any, label: str, cls: str = "") -> str:
    ncls = f" {cls}" if cls else ""
    return f"<div class='tile'><div class='n{ncls}'>{esc(number)}</div><div class='l'>{esc(label)}</div></div>"


def tiles(items: Iterable[str]) -> str:
    return "<div class='tiles'>" + "".join(items) + "</div>"


def status_pill(status: str) -> str:
    cls = {"PASS": "pass", "FAIL": "fail", "WARN": "warn",
           "INFO": "info", "NOT_COMPUTABLE": "nc"}.get(status, "nc")
    return f"<span class='pill {cls}'>{esc(status)}</span>"


def sev_pill(severity: str) -> str:
    """Pill for the Layer B/C severity model (ERROR/WARN/INFO/BLOCKED/CEILING/FORMAT_GAP/PASS)."""
    cls = {"PASS": "pass", "ERROR": "err", "WARN": "warn", "INFO": "info",
           "BLOCKED": "blk", "CEILING": "ceil", "FORMAT_GAP": "gap"}.get(severity, "nc")
    return f"<span class='pill {cls}'>{esc(severity)}</span>"


def table(headers: List[str], rows: List[List[str]]) -> str:
    if not rows:
        return "<p class='sub'>none</p>"
    head = "".join(f"<th>{esc(h)}</th>" for h in headers)
    body = "".join("<tr>" + "".join(f"<td>{c}</td>" for c in r) + "</tr>" for r in rows)
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"
